### ISSUE TITLE
[1.12.2] Ice and Fire dragon internal server error kick

### ISSUE THREAD

**Issue by arceusplayer11** [asanetargoss/metamorph#14]
Whenever I try to morph into either a fire or ice dragon from Ice and Fire, I get kicked from my server with an internal server error. The server spits out this error:

`[22:47:19] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.PlaySoundAtEntityEvent@514f6196:
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/culling/ICamera
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_242]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_242]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_242]
        at mchorse.metamorph.util.InvokeUtil.getPrivateMethod(InvokeUtil.java:21) ~[InvokeUtil.class:?]
        at mchorse.metamorph.api.morphs.EntityMorph.playStepSound(EntityMorph.java:843) ~[EntityMorph.class:?]
        at mchorse.metamorph.entity.SoundHandler.onPlaySound(SoundHandler.java:127) ~[SoundHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1848_SoundHandler_onPlaySound_PlaySoundAtEntityEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703) [EventBus.class:?]
        at net.minecraftforge.event.ForgeEventFactory.onPlaySoundAtEntity(ForgeEventFactory.java:498) [ForgeEventFactory.class:?]
        at net.minecraft.world.World.func_184148_a(World.java:1121) [amu.class:?]
        at net.minecraft.entity.player.EntityPlayer.redirect$zgl000$spongePlaySound(EntityPlayer.java:43938) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_184185_a(EntityPlayer.java:403) [aed.class:?]
        at net.minecraft.entity.Entity.func_180429_a(Entity.java:1079) [vg.class:?]
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:953) [vg.class:?]
        at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827) [aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513) [aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$zii000$impl$onPlayerTick(NetHandlerPlayServer.java:2504) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.culling.ICamera
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
        ... 33 more
[22:47:19] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[22:47:19] [Server thread/ERROR] [FML]: 0: NORMAL
[22:47:19] [Server thread/ERROR] [FML]: 1: ASM: mchorse.metamorph.entity.SoundHandler@31985c4d onPlaySound(Lnet/minecraftforge/event/entity/PlaySoundAtEntityEvent;)V`

From what I can tell, it has something to do with playing sounds. The crash usually happens when I'm in the air/when I jump. I've tried changing the config to both turn on idle mob sounds and turn them off, but neither fixes the kicks.

**Comment by asanetargoss** [comment]
Does this happen with other mobs, or only Ice and Fire mobs? And if so, which ones?

**Comment by arceusplayer11** [comment]
Only Fire and Ice mobs from what I can tell. In particular, the Ice dragons, and the Fire dragons. I tested sea serpents and they seem to work fine, if a bit weirdly; no crashes

**Comment by asanetargoss** [comment]
Hmm, it sounds like it could be something involving Ice and Fire referencing client code on the server  side. But we'll see.

**Comment by asanetargoss** [comment]
Hello again, can you please specify the mods you used to reproduce this crash, including:

- Forge version
- Ice and Fire version
- LLib version
- Changeling version
- DominionLib or McLib version

**Comment by asanetargoss** [comment]
Hello, please try downloading the latest version of Changeling and DominionLib and see if they fix your issue.
