### ISSUE TITLE
NoClassDefFoundError when morphing into pig

### ISSUE THREAD

**Issue by asanetargoss** [asanetargoss/metamorph#6]
https://www.curseforge.com/minecraft/mc-mods/changeling?comment=34

Occurring on 1.12. Player says it occurred when morphing into a pig with Animania installed. Player most likely meant a pig mob variant from the Animania mod.

```
WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  McLib core mod (mclib-1.0.3-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge
 
// My bad.
 
Time: 10/12/19 9:14 AM
Description: Ticking entity
 
java.lang.NoClassDefFoundError: mcjty/theoneprobe/api/ProbeMode
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    at java.lang.Class.getDeclaredMethods(Class.java:1975)
    at mchorse.metamorph.util.InvokeUtil.getPrivateMethod(InvokeUtil.java:21)
    at mchorse.metamorph.api.morphs.EntityMorph.playStepSound(EntityMorph.java:839)
    at mchorse.metamorph.entity.SoundHandler.onPlaySound(SoundHandler.java:117)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_543_SoundHandler_onPlaySound_PlaySoundAtEntityEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.onPlaySoundAtEntity(ForgeEventFactory.java:498)
    at net.minecraft.client.entity.EntityPlayerSP.func_184185_a(EntityPlayerSP.java:581)
```

**Comment by asanetargoss** [comment]
This crash has been fixed for 1.12 on Animania's side. If you are using Animania on 1.12, please update to the latest version of Animania.
